const bar = document.getElementById('bar');
const close = document.getElementById('close');
const nav = document.getElementById('navbar');

if (bar) {
  bar.addEventListener('click', () => {
    nav.classList.add('active');
  });
}
if (close) {
  close.addEventListener('click', () => {
    nav.classList.remove('active');
  });
}

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: 'AIzaSyC2oniNeVN8wB6-1cu9b79b19xqUikE8F4',
  authDomain: 'woodworks-fc103.firebaseapp.com',
  projectId: 'woodworks-fc103',
  storageBucket: 'woodworks-fc103.appspot.com',
  messagingSenderId: '461817913357',
  appId: '1:461817913357:web:e61d48d1d04a1106853544',
  measurementId: 'G-EH76FEP18Z',
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);

function buy() {
  var productsFirebase = [];
  for (let index = 0; index < products.length; index++) {
    if (products[index].cart) {
      var product = {
        prodname: products[index].prodname,
        price: products[index].price,
        quantity: products[index].quantity,
        total: products[index].total,
      };
      productsFirebase.push(product);
    }
  }
  firebase().database().ref('cart').push({
    total: total(),
    products: productsFirebase,
  });
  Swal.fire({
    type: 'success',
    title: 'Success',
    text: 'Operation Completed'
  });
  clean();
}

var products = [
  {
    "handleId": "product_2ddcef41-738d-b1f4-36e6-d72d012bce42",
    "fieldType": "Product",
    "name": "NODELAND Wardrobe",
    "description": "<p>Adjustable shelves make it easy to customize the space according to your needs. Perfect for folded as well as long and short hanging clothes.</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Width:</strong> 80.0 cm (31 1/2 \")</p><p><strong>Depth:</strong> 51.6 cm (20 3/8 \")</p><p><strong>Height: </strong>202.0 cm (79 1/2 \")</p><p><strong>Frame/ Door panel/ Shelf/ Plinth back/ Plinth front:</strong>&nbsp;Particleboard, Melamine foil, Plastic edging</p><p><strong>Back panel:</strong>&nbsp;Fiberboard, Paper foil</p><p><strong>Fixing bracket:</strong> Steel, Galvanized</p><p>&nbsp;</p>",
    "productImageUrl": "ab0b93_bb4e47e1daae453ca22a10780de527a7~mv2.png;ab0b93_df5420bdda7146589e5cec0fd440cdc9~mv2.png",
    "collection": "Wardrobe",
    "sku": 17,
    "ribbon": "Wardrobe",
    "price": 6255,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_35109a01-f996-0f2c-1604-1e955dd94bdc",
    "fieldType": "Product",
    "name": "4 Tier Wooden Display Cabinet",
    "description": "<p>Have a limited space at home or office but still need a compact and space-saving display cabinet? We highly recommend our 4-Tier Wooden Display Cabinet as a beautiful and functional storage solution for your precious mementos and knick-knacks. Handcrafted and hand-polished, this 4-tier display cabinet features 2 levels with 2 pull-out doors and uneven placement of gold-finished handles. Each level has 2 separate shelves, lending you ample space for all your figurines, books, or travel souvenirs. This furniture works perfectly in traditional and country home interior design style.</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Size (LxBxH):</strong> 24 x 12 x 42 Inch</p><p><strong>Material: </strong>Teak wood</p><p><strong>Ship by:</strong> 2 to 3 Week</p><p><strong>Assembly Required: </strong>Shipped in Part(s)</p><p>&nbsp;</p>",
    "productImageUrl": "ab0b93_16356f89e223497099ae9aa07967bd11~mv2.png;ab0b93_a0aeef4983ac48b4a3fe01fb73a75a1a~mv2.png",
    "collection": "Featured Products;Showcase",
    "sku": 16,
    "ribbon": "Showcase",
    "price": 3000,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_b4e6add3-09ea-0dd0-9f5c-ceecadb43034",
    "fieldType": "Product",
    "name": "606 Dresser",
    "description": "<p><strong>Dimensions:</strong> H65.5″ x L31.25″ x D16″</p><p><strong>Material: </strong>MDF</p><p><strong>Color: </strong>Columbia Oak or Hudson Oak</p>",
    "productImageUrl": "ab0b93_5b19b35a98c946ae90d85cae2443d68f~mv2.png",
    "collection": "Dressers",
    "sku": 15,
    "ribbon": "Dressing Table",
    "price": 6500,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_1f1b548b-c84d-433a-4c26-3c4f640a0593",
    "fieldType": "Product",
    "name": "Ward Dresser with Stool",
    "description": "<p>The large drawer is perfect for storing things like hairdryers, curling irons, sprays or other larger items that take up a lot of space. There’s plenty of space for makeup and jewelry in the wide, felt-lined drawer.</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Dimensions: </strong>W80 x D40 x H160cm</p><p><strong>Dresser:</strong>&nbsp;25mm thick MDF board table top and 15mm thick MDF board door and drawer front laminated with PVC vinyl. 15mm thick particle board with paper laminate in carcass frame and with 3mm thick mirror glass and 32mm diameter round metal knob handle.</p><p><strong>Stool: </strong>15mm thick Particle board with paper laminate with 50mm new foam covered with PU faux leather.</p><p>&nbsp;</p>",
    "productImageUrl": "ab0b93_869135c80d2c43d1811d9d2d8e4fc6b4~mv2.png;ab0b93_59d19f0fe19b4d44b000d31bf88e5c2c~mv2.png;ab0b93_da37f04cc7154dcb8eb9d26f9e8f2f55~mv2.png",
    "collection": "Dressers",
    "sku": 14,
    "ribbon": "Dressing Table",
    "price": 5550,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_549147e9-7b6e-56b4-3ed0-0a0fc0718876",
    "fieldType": "Product",
    "name": "SYVDE Dressing Table",
    "description": "<p>When it’s time to get ready in the morning, have a seat at SYVDE dressing table. The clean, simple design is easy to place and the two drawers put make-up, accessories and hair supplies within easy reach. The large drawer is perfect for storing things like hairdryers, curling irons, sprays or other larger items that take up a lot of space. There’s plenty of space for makeup and jewelry in the wide, felt-lined drawer.</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Width:</strong> 100.3 cm (39 1/2 \")</p><p><strong>Depth: </strong>48.2 cm (19 \")</p><p><strong>Height: </strong>78 cm (30 3/4 \")</p><p><strong>Top panel/ Partition/ Drawer front:</strong>&nbsp;Particleboard, Acrylic paint, Paper foil, Plastic edging</p><p><strong>Top:</strong>&nbsp;Tempered glass, Glass enamel</p><p><strong>Side panel:</strong>&nbsp;Particleboard, Acrylic paint, Plastic edging</p><p><strong>Back panel/ Front rail:</strong>&nbsp;Particleboard, Paper foil, Plastic edging</p><p><strong>Drawer side/ Drawer back/ Drawer divider:</strong>&nbsp;Particleboard, Plastic foil</p><p><strong>Drawer bottom:</strong>&nbsp;Fiberboard, Acrylic paint</p><p><strong>Drawer mat:</strong> 100 % polyester</p>",
    "productImageUrl": "ab0b93_10841838a67843999e7e71bd1d64cf64~mv2.png;ab0b93_765e34adcd7e4695b5190ed5ad4a43cd~mv2.png",
    "collection": "Dressers",
    "sku": 13,
    "ribbon": "Dressing Table",
    "price": 7090,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_0982deea-c1c2-8f0f-14bf-ce896228e2f2",
    "fieldType": "Product",
    "name": "Cabello Base Cabinet",
    "description": "<p>Cabello Base Cabinet combines the storage of a 20 inch long drawer and the versatility of a door that can be easily mounted to open left or right. The heavy duty drawer has a half-inch thick bottom and metal sides that roll on smooth roller glides, making it perfect for storing heavy duty items like tools. The cabinet includes one adjustable shelf and 1” thick worktop. Customizable, functional and durable, it coordinates perfectly with other pieces in the Elite Collection.</p>",
    "productImageUrl": "ab0b93_5a87c80a1c7245f9bf0de8258d4782df~mv2.png;ab0b93_67ebe37810814dde8b12ebfe4c5befa1~mv2.png;ab0b93_6c39286ac3414fbd90c6b9a4f60642c4~mv2.png",
    "collection": "Base Cabinet",
    "sku": 12,
    "ribbon": "Base Cabinet",
    "price": 6500,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_1a335095-c420-4aca-782d-36bf0f8aee06",
    "fieldType": "Product",
    "name": "KNOXHULT Base Cabinet",
    "description": "<p>KNOXHULT modular kitchen makes it easier to plan, design and survive the kitchen jungle. Combine the modules, add knobs or handles, and finish with functions like organisers, waste management and lighting. Material: Kichen cabinet: Particleboard.&nbsp;</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Material:</strong> Kichen cabinet: Particleboard</p><p><strong>Countertop length:</strong> 122cm (48”)</p>",
    "productImageUrl": "ab0b93_bfad1fa2aae44c0294e4db13850f387f~mv2.png;ab0b93_873f8bcc1ffb4f80ab9a9b0a87874292~mv2.png;ab0b93_8222e5a0024e43cdb5e4a10ab1823ba0~mv2.png",
    "collection": "Base Cabinet;Featured Products",
    "sku": 11,
    "ribbon": "Base Cabinet",
    "price": 10990,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_85585b4a-f11e-b7fa-c474-4ef0499c71ee",
    "fieldType": "Product",
    "name": "1105 Kitchen Cabinet",
    "description": "<p>Adjustable hinges allow you to adjust the door horizontally and vertically. The Glass-door cabinet keeps your favorite items free from dust but still visible. This can be used on the corner unit only if the shelf next to it has no doors.&nbsp;</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Material: </strong>MDF</p><p><strong>Color:</strong> Columbia Oak or Hudson Oak</p><p><strong>Dimension:</strong> H79.75″ x L31.5″ x D17″</p>",
    "productImageUrl": "ab0b93_47375c9f7b2a4e0cb20d74c28546006d~mv2.png",
    "collection": "Base Cabinet;Featured Products",
    "sku": 10,
    "ribbon": "Base Cabinet",
    "price": 8990,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_c2ec8a2d-101b-8c53-2c04-985963629c5e",
    "fieldType": "Product",
    "name": "Oxberg Glass Door",
    "description": "<p>Adjustable hinges allow you to adjust the door horizontally and vertically. The Glass-door cabinet keeps your favorite items free from dust but still visible. This can be used on the corner unit only if the shelf next to it has no doors.&nbsp;</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Width: </strong>40 cm (15 3/4 \")</p><p><strong>Height: </strong>192 cm (75 5/8 \")</p>",
    "productImageUrl": "ab0b93_0fa9ea280bf94c02aae7fcd087ae1da5~mv2.png;ab0b93_ece4e255e2194217a125894410a48fdb~mv2.png",
    "collection": "Corner Cabinet;Featured Products",
    "sku": 9,
    "ribbon": "Corner Cabinet",
    "price": 2000,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_d6e3483f-5c4e-1abd-7b8b-148a4da2e1c2",
    "fieldType": "Product",
    "name": "Usikey 3 Tier Shelf Floor Storage Cabinet",
    "description": "<ul>\t<li>\t<p>FANTASTIC SOLUTION FOR SMALL SPACE: Wants a expanding storage space in your apartment? this tall standing cabinet occupy little valuable floor space while offers ample storage space, it is a ideal option for your small apartment or room, This corner cabinet makes full use of limited space and offers versatile storage solutions for the bathroom, bedroom, living room, hallway and the corner space.</p>\t</li></ul><p>&nbsp;</p><ul>\t<li>\t<p>SWITCHABLE SHELVING RACK: Three spacious shelves and two large drawers expand your storage space, you can change the position of the drawer according to your different needs, with plenty of storage space for you to arrange your towels, plants or cosmetics, the versatile cabinet will make your home more tidy.</p>\t</li></ul><p>&nbsp;</p><ul>\t<li>\t<p>EXCELLENT STABILITY &amp; SAFE MATERIAL : No one likes wobbly furniture! Stability and security are always the first, the stable construction of USIKEY tall floor cabinet ensures a safe stand, the included anti-toppling fittings even makes it more stable. Meanwhile this storage cabinet is made of certified particle board, poisonless and tasteless, ensure a long-time use and easy cleaning.</p>\t</li></ul><p>&nbsp;</p><ul>\t<li>\t<p>EASY ASSEMBLY: Our storage cabinet needs some simple steps, coming with picture directions, every part is clearly marked and you will find it’s easy to assemble even if you aren’t a DIY guy. Pretty and functional, once you finish building it, you will be attracted by its elegant appearance.</p>\t</li></ul><p>&nbsp;</p><ul>\t<li>\t<p>SIZE :Overall Size: 11.8\" x 11.8\" x 55.9\"(L x W x H). Overall drawer size: 9.25\" x 10.43\" x 8.27\"(L x W x H). Weight: 26.5 lbs</p>\t</li></ul><p>&nbsp;</p><p>&nbsp;</p>",
    "productImageUrl": "ab0b93_e45fca510ed84c6bbf9941fa75e39a36~mv2.png;ab0b93_062be5ea7c3544c2b7aea59e10f0f035~mv2.png",
    "collection": "Corner Cabinet;Featured Products",
    "sku": 8,
    "ribbon": "Corner Cabinet",
    "price": 5600,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_dc675221-0555-936f-f99c-8e9958fff61c",
    "fieldType": "Product",
    "name": "Teak Corner Cabinet",
    "description": "",
    "productImageUrl": "ab0b93_36b966b7f6664702ba2d04f5309acafc~mv2.png;ab0b93_38fd0683a28c4b338b8caaf5e5421a34~mv2.png;ab0b93_2214b9bedbce4980beed74bd834c2bd7~mv2.png",
    "collection": "Corner Cabinet",
    "sku": 7,
    "ribbon": "Corner Cabinet",
    "price": 42000,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_586dd135-fc17-2831-d8cd-8612ec3afb43",
    "fieldType": "Product",
    "name": "Wooden Angled Corner Showcase",
    "description": "<p>This wooden showcase has stylish exteriors and interiors. The unique pentagonal shape makes it a class-apart. The showcase features four towering glass racks inside, with wooden framed glass panelled walls and doors on the three sides. You can keep your favourite book collections or your treasured trinkets in the showcase. You can also organise different items in different racks. The angular shape and glass panels provide the maximum visibility. And what’s better when your collectibles can be seen from any corner of your room? So go ahead, and give a corner of your living room or bedroom a stylish makeover.</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Size (LxBxH): </strong>21 x 2 3 x 48 Inch</p><p><strong>Material: </strong>Teak wood</p><p><strong>Ship by:</strong> 2 to 3 Week</p><p><strong>Assembly Required:</strong> No</p>",
    "productImageUrl": "ab0b93_a5a5660d555c4403b21cbcaf2b5cfb85~mv2.png;ab0b93_e11e86193eed4647993c9f74b6bc0acd~mv2.png",
    "collection": "Corner Cabinet;Featured Products",
    "sku": 6,
    "ribbon": "Corner Cabinet",
    "price": 15500,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_7fb42104-daae-1dd1-f781-37ca9a3fb2c7",
    "fieldType": "Product",
    "name": "Triple Storage Night Stand",
    "description": "<p>The bedside area is a crucial one that has to be designed in just the right way so that when we fumble for an essential item in the middle of the night, we may find it with ease. This could be medicines, water or a number of other things that would be placed next to a lamp. This means that the night stand or the bedside table has to be large enough to hold all these items with ease. This wide bedside table with the three drawers and the open shelf will give you more than enough space to access and store some books of your choice along with a water jug and glass that would not be too close to get knocked down.</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Size (LxBxH):</strong> 20 x 15 x 24 Inch</p><p><strong>Material:</strong> Natural Solid wood</p><p><strong>Ship by:</strong> 2 to 3 Week</p><p><strong>Assembly Required:</strong> No</p>",
    "productImageUrl": "ab0b93_19a028d842444958b69d447faf00a2cb~mv2.png;ab0b93_a5a72ab79e2a4c39b7c7f4d7c7b4970b~mv2.png;ab0b93_cb368034c3a64b6d91f6f7f667588c1b~mv2.png",
    "collection": "Bedside;Featured Products",
    "sku": 5,
    "ribbon": "Bedside",
    "price": 5200,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_fceee641-2ada-e1b8-c1da-58bddb3436ba",
    "fieldType": "Product",
    "name": "Light Finish 3-Drawer Bedside Unit",
    "description": "<p>A practical bedside unit with a classy light finish that would make a great addition to your bedroom. With three drawers and two cubby holes it has enough storage space to accommodate your nightly routine. Whether your bedside unit is cluttered with chargers and devices or tastefully decorated with a lampshade or a nightlight or just kept simply well organised: this unit would fit the bill no matter how you keep it. The light finishing is such that it matches well with your interiors whether they are traditional or contemporary. A fine piece to keep by your bedside with just the right storage spaces which makes it a beautiful combination of style and utility.</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Size (LxBxH):</strong> 20 x 15 x 24 Inch</p><p><strong>Material:</strong> Natural Solid wood</p><p><strong>Ship by</strong>: 2 to 3 Week</p><p><strong>Assembly Required: </strong>No</p><p>&nbsp;</p>",
    "productImageUrl": "ab0b93_d9e244336c714943a19318e434b84177~mv2.png;ab0b93_6bc496b52744457fa7625e29b5abb54e~mv2.png",
    "collection": "Bedside;Featured Products",
    "sku": 4,
    "ribbon": "Bedside",
    "price": 5300,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_312c8ebc-873b-ee45-0693-a51bbf387cd4",
    "fieldType": "Product",
    "name": "Simple Night Stand",
    "description": "<p>Simplicity and robustness join hands in this nightstand, carved and crafted from matured teak wood - for your comfort! Your bedroom could do with a piece like this, since it offers the best of storage space along with a no-frills design. The sturdy good looks come from naturally polished teak, so that the real wooden grain shines like the superstar of the furniture industry!</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Size (LxBxH):</strong> 18 x 11 x 28 Inch</p><p><strong>Material:</strong> Teak wood</p><p><strong>Ship by:</strong> 2 to 3 Week</p><p><strong>Assembly Required:</strong> No</p>",
    "productImageUrl": "ab0b93_03f411577f244ac1b797047f1d9b59df~mv2.png;ab0b93_4ce62bc5928543518d4c20428f28cf4f~mv2.png;ab0b93_094c66a7be8e41bbb8aa0898393f4530~mv2.png",
    "collection": "Bedside;Featured Products",
    "sku": 3,
    "ribbon": "Bedside",
    "price": 5100,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_fa4b1183-2945-0ca7-0358-81f33f948daa",
    "fieldType": "Product",
    "name": "Double Storage Bedside Table",
    "description": "<p>In the night, there are a number of things that we often reach out for. Whether it is a medicine, a glass of water or even the phone, we wake up a few times and look out for such objects. This is why you need a solid and sturdy bedside table. While the top can accommodate a number of items, you want to be sure that you do not over clutter it since this can put you at risk of knocking over some items in the middle of the night. This is why we have organized the structure with an open storage compartment and two roomy drawers that slide in and out with symmetrical and well crafted perfection for your convenience.</p><p>&nbsp;</p><p><strong>Measurement/Specifications</strong></p><p>&nbsp;</p><p><strong>Size (LxBxH):</strong> 18 x 16 x 20 Inch</p><p><strong>Material:</strong> Natural Solid wood</p><p><strong>Ship by</strong>: 2 to 3 Week</p><p><strong>Assembly Required:</strong> No</p>",
    "productImageUrl": "ab0b93_016682a4caec4772a2c39f055fd53eb2~mv2.png;ab0b93_7e9c1e3f8c4b42098f7d0c0384f320d5~mv2.png",
    "collection": "Bedside;Featured Products",
    "sku": 1,
    "ribbon": "Bedside",
    "price": 5200,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  },
  {
    "handleId": "product_4ac941ca-c525-d3de-f51c-f4d64c53a53d",
    "fieldType": "Product",
    "name": "Charming Teak Night Stand",
    "description": "<p>The teak wood and the charming curved legs in the small size make this piece a must have for your home. You can use this teak wood night stand next to the bed or you can even bring it into your living room as an end table that also doubles as a storage unit for odds and ends as well as papers that you do not easily find! The light polish makes it a good looking piece.</p><p>&nbsp;</p><p><strong>Size (LxBxH):</strong> 11 x 11 x 12 Inch</p><p><strong>Material:</strong> Teak wood</p><p><strong>Ship by:</strong> 1 to 2 Weeks</p><p><strong>Assembly Required:</strong> No</p>",
    "productImageUrl": "ab0b93_84a7a0615f94417db859726f15f3db23~mv2.png;ab0b93_66a308d6cabc4be8b88c9763594938bf~mv2.png;ab0b93_d55536b84ab0477fb6202e34df6c843a~mv2.png",
    "collection": "Bedside",
    "sku": 2,
    "ribbon": "Bedside",
    "price": 3400,
    "surcharge": "",
    "visible": true,
    "discountMode": "PERCENT",
    "discountValue": 0,
    "inventory": "InStock",
    "weight": 0,
    "cost": "",
    "productOptionName1": "",
    "productOptionType1": "",
    "productOptionDescription1": "",
    "productOptionName2": "",
    "productOptionType2": "",
    "productOptionDescription2": "",
    "productOptionName3": "",
    "productOptionType3": "",
    "productOptionDescription3": "",
    "productOptionName4": "",
    "productOptionType4": "",
    "productOptionDescription4": "",
    "productOptionName5": "",
    "productOptionType5": "",
    "productOptionDescription5": "",
    "productOptionName6": "",
    "productOptionType6": "",
    "productOptionDescription6": "",
    "additionalInfoTitle1": "",
    "additionalInfoDescription1": "",
    "additionalInfoTitle2": "",
    "additionalInfoDescription2": "",
    "additionalInfoTitle3": "",
    "additionalInfoDescription3": "",
    "additionalInfoTitle4": "",
    "additionalInfoDescription4": "",
    "additionalInfoTitle5": "",
    "additionalInfoDescription5": "",
    "additionalInfoTitle6": "",
    "additionalInfoDescription6": "",
    "customTextField1": "",
    "customTextCharLimit1": "",
    "customTextMandatory1": "",
    "customTextField2": "",
    "customTextCharLimit2": "",
    "customTextMandatory2": "",
    "brand": ""
  }

// RENDER
(() => {
  for (let index = 0; index < products.length; index++) {
    document.getElementById('row1').innerHTML += `
    <h2>${products [index].prodname}</h2>
        `;
  }
})();
